### ISSUE TITLE
Lsass minidump and pypykatz module on Linux

### ISSUE THREAD

**Issue by laxa** [ufrisk/MemProcFS#175]
Hello, as stated on the documentation: https://github.com/ufrisk/MemProcFS/wiki/FS_Process_Minidump, the LSASS minidump should be readable by pypykatz but this is currently not the case:

```
$ ./memprocfs -mount /home/laxa/test -device /home/laxa/Downloads/DESKTOP-K8H8365-20230417-143508.dmp
Initialized 64-bit Windows 10.0.19041

=============== MemProcFS - THE MEMORY PROCESS FILE SYSTEM ===============
 - Author:           Ulf Frisk - pcileech@frizk.net
 - Info:             https://github.com/ufrisk/MemProcFS
 - License:          GNU Affero General Public License v3.0
   --------------------------------------------------------------------
   MemProcFS is free open source software. If you find it useful please
   become a sponsor at: https://github.com/sponsors/ufrisk Thank You :)
   --------------------------------------------------------------------
 - Version:          5.5.0 (Linux)
 - Mount Point:      /home/laxa/test
 - Tag:              19041_436be1f0
 - Operating System: Windows 10.0.19041 (X64)
==========================================================================
[...]
$ pypykatz lsa minidump minidump.dmp
INFO:pypykatz:Parsing file minidump.dmp
ERROR:pypykatz:Minidump parsing error!
Traceback (most recent call last):
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 139, in parse_minidump_file
    minidump = MinidumpFile.parse(filename)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 49, in parse
    mf._parse()
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 80, in _parse
    self.__parse_directories()
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 113, in __parse_directories
    self.modules = MinidumpModuleList.parse(dir, self.file_handle)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/streams/ModuleListStream.py", line 231, in parse
    t.modules.append(MinidumpModule.parse(mod, buff))
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/streams/ModuleListStream.py", line 31, in parse
    mm.name = MINIDUMP_STRING.get_from_rva(mod.ModuleNameRva, buff)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/common_structs.py", line 86, in get_from_rva
    return ms.Buffer.decode('utf-16-le')
  File "/usr/lib/python3.9/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 184-185: illegal encoding
ERROR:pypykatz:Error while parsing file minidump.dmp
Traceback (most recent call last):
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/lsadecryptor/cmdhelper.py", line 260, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile, packages=args.packages)
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 144, in parse_minidump_file
    raise e
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 139, in parse_minidump_file
    minidump = MinidumpFile.parse(filename)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 49, in parse
    mf._parse()
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 80, in _parse
    self.__parse_directories()
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 113, in __parse_directories
    self.modules = MinidumpModuleList.parse(dir, self.file_handle)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/streams/ModuleListStream.py", line 231, in parse
    t.modules.append(MinidumpModule.parse(mod, buff))
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/streams/ModuleListStream.py", line 31, in parse
    mm.name = MINIDUMP_STRING.get_from_rva(mod.ModuleNameRva, buff)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/common_structs.py", line 86, in get_from_rva
    return ms.Buffer.decode('utf-16-le')
  File "/usr/lib/python3.9/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 184-185: illegal encoding
ERROR:pypykatz:Error while parsing file minidump.dmp
Traceback (most recent call last):
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/lsadecryptor/cmdhelper.py", line 260, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile, packages=args.packages)
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 144, in parse_minidump_file
    raise e
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 139, in parse_minidump_file
    minidump = MinidumpFile.parse(filename)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 49, in parse
    mf._parse()
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 80, in _parse
    self.__parse_directories()
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 113, in __parse_directories
    self.modules = MinidumpModuleList.parse(dir, self.file_handle)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/streams/ModuleListStream.py", line 231, in parse
    t.modules.append(MinidumpModule.parse(mod, buff))
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/streams/ModuleListStream.py", line 31, in parse
    mm.name = MINIDUMP_STRING.get_from_rva(mod.ModuleNameRva, buff)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/common_structs.py", line 86, in get_from_rva
    return ms.Buffer.decode('utf-16-le')
  File "/usr/lib/python3.9/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 184-185: illegal encoding
Traceback (most recent call last):
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/lsadecryptor/cmdhelper.py", line 260, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile, packages=args.packages)
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 144, in parse_minidump_file
    raise e
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 139, in parse_minidump_file
    minidump = MinidumpFile.parse(filename)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 49, in parse
    mf._parse()
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 80, in _parse
    self.__parse_directories()
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/minidumpfile.py", line 113, in __parse_directories
    self.modules = MinidumpModuleList.parse(dir, self.file_handle)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/streams/ModuleListStream.py", line 231, in parse
    t.modules.append(MinidumpModule.parse(mod, buff))
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/streams/ModuleListStream.py", line 31, in parse
    mm.name = MINIDUMP_STRING.get_from_rva(mod.ModuleNameRva, buff)
  File "/home/laxa/.local/lib/python3.9/site-packages/minidump/common_structs.py", line 86, in get_from_rva
    return ms.Buffer.decode('utf-16-le')
  File "/usr/lib/python3.9/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 184-185: illegal encoding
```

Moreover, the `py/secrets` module is also failing:

```
$ cat parsing_error.txt 

pypykatz plugin tried to parse the lsass.exe process in your memory dump but failed.
This could be caused by multiple things:
        1. The pypykatz's parser code is potato
        2. MemProcFs could not fully parse the memory, usually this happens with incorrect memory dump files.
                Check for error strings like "Could not load segment data"

In case you are cretain the problem is caused by the parser, 
please submit an issue with the info below this line:
===== BASIC INFO. SUBMIT THIS IF THERE IS AN ISSUE =====
CPU arch: X64
OS: None
BuildNumber: 19041
MajorVersion: 6
MSV timestamp: 3191709088


Traceback (most recent call last):
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 261, in get_lsa
    lsa_dec = LsaDecryptor.choose(self.reader, lsa_dec_template, self.sysinfo)
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/lsadecryptor/lsa_decryptor.py", line 20, in choose
    return LsaDecryptor_NT6(reader, decryptor_template, sysinfo)
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/lsadecryptor/lsa_decryptor_nt6.py", line 22, in __init__
    self.acquire_crypto_material()
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/lsadecryptor/lsa_decryptor_nt6.py", line 26, in acquire_crypto_material
    sigpos = self.find_signature()
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/lsadecryptor/lsa_decryptor_nt6.py", line 44, in find_signature
    fl = self.reader.find_in_module('lsasrv.dll', self.decryptor_template.key_pattern.signature, find_first = True)
TypeError: find_in_module() got an unexpected keyword argument 'find_first'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laxa/Downloads/plugins/pym_pypykatz/pym_pypykatz.py", line 107, in process_lsass
    mimi.start()
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 350, in start
    self.lsa_decryptor = self.get_lsa()
  File "/home/laxa/.local/lib/python3.9/site-packages/pypykatz/pypykatz.py", line 267, in get_lsa
    raise Exception('All detection methods failed.')
Exception: All detection methods failed.
```

Windows dump has been made with `DumpIt` with latest Windows 10 patch (10.0.19045 N/A Build 19045), let me know if further information is required. I used the latest provided build: https://github.com/ufrisk/MemProcFS/releases/download/v5.5/MemProcFS_files_and_binaries_v5.5.0-linux_x64-20230417.tar.gz.

**Comment by ufrisk** [comment]
If you copy the minidump file over to Windows and load it into Mimikatz proper, does it work?

If not, does it work to open it in windbg on Windows?

**Comment by ufrisk** [comment]
I'm closing this issue since I haven't heard back. I'm assuming there was an issue in the pypykatz dependency.

Let me know if the error persists on the latest mimikatz.

**Comment by laxa** [comment]
Hello, it does not work with mimikatz either. I dont have windbg but could try to install to check if that works.

**Comment by ufrisk** [comment]
Thanks, my best guess is that it's the:
```
Dir entry 0, ThreadListStream stream stream size mismatch (0x1b8 != 0x1b4)
Dir entry 2, ModuleListStream stream stream size mismatch (0x28b8 != 0x2740)
```
that are causing the issues and that there is a bug. My main issue is that I don't get these.

Would it be possible to share the full memory dump file from which this minidump file is generated? I totally understand if it's not possible since lsass may contain sensitive information. But if you are able to share it (or another one with the same issue from a lab system) it would make my work much easier in tracking this down.

**Comment by laxa** [comment]
Thank you for your time, I have pmed you on twitter the details to retrieve the full dump.

**Comment by ufrisk** [comment]
This seems to be an issue with the Linux version of MemProcFS. I'll look into it.

**Comment by ufrisk** [comment]
This should now be fixed. No need to update any blog entries or such tho. But issue should be resolved at last.
